try:
    # The _version.py file is generated by setuptools_scm during release and should contain the right version number
    from ._version import version, __version__, version_tuple, __version_tuple__
except ImportError:
    # The case where this file does not exist is: during development. In this case, we set the version to unknown, such
    # that at least we don't crash when trying to get the version number.
    version = __version__ = "0.0.0+unknown"
    __version_tuple__ = version_tuple = (0, 0, 0, 'unknown')
