# Generated by Django 4.2.18 on 2025-02-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_b_squashed_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["name"], name="teams_team_name_43e047_idx"),
        ),
    ]
