# Generated by Django 4.2.16 on 2025-01-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="slug",
        ),
    ]
