# Generated by Django 4.2.23 on 2025-07-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh_Hans', 'Simplified Chinese')], default='en', max_length=10),
        ),
    ]
