# Generated by Django 4.2.23 on 2025-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto'), ('en', 'English'), ('zh-Hans', 'Simplified Chinese')], default='auto', max_length=10),
        ),
    ]
