# Generated by Django 4.2.19 on 2025-04-11 11:33

import bsmain.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=bsmain.models.generate_token,
                        max_length=40,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Token must be a 40-character hexadecimal string.",
                                regex="^[a-f0-9]{40}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
