# Generated by Django 5.2.11 on 2026-02-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsmain', '0002_cachedmodelcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
