# Generated by Django 5.2.15 on 2026-09-08 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsmain', '0003_add_description_to_authtoken'),
        ('projects', '0019_alter_project_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='is_project_bound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='debug_files_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='events_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='issues_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='issues_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='issues_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='issues_triage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='is_user_bound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='auth_tokens',
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='projects_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='projects_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='releases_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='releases_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='teams_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='teams_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='auth_tokens',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='description',
            field=models.CharField(default='Unnamed token', max_length=255),
        ),
    ]
