# Generated by Django 4.2.18 on 2025-02-03 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),  # the previous migration
        ("issues", "0001_initial"),  # This defines the Grouping model, which the below FKs to

        # Additionally, Django auto-detected the below, presumably because we add a (project, event_id) unique
        # constraint. However, we don't actually depend on this migration when adding that constraint, so we don't need
        # to depend on it here.
        # ("projects", "0002_b_squashed_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="ingest_order",
            new_name="digest_order",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="server_side_timestamp",
            new_name="digested_at",
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("project", "event_id"), ("issue", "digest_order")},
        ),
        migrations.AddField(
            model_name="event",
            name="grouping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="issues.grouping",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ingested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="irrelevance_for_retention",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="never_evict",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=[
                    "project",
                    "never_evict",
                    "digested_at",
                    "irrelevance_for_retention",
                ],
                name="events_even_project_ac6fc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["issue", "digested_at"], name="events_even_issue_i_b18956_idx"
            ),
        ),
    ]
