# Generated by Django 4.2.13 on 2024-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_irrelevance_for_retention'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'server_side_timestamp', 'irrelevance_for_retention'], name='events_even_project_abe572_idx'),
        ),
    ]
