# Generated by Django 4.2.13 on 2024-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_events_even_project_abe572_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='never_evict',
            field=models.BooleanField(default=False),
        ),
    ]
