# Generated by Django 4.2.13 on 2024-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_events_even_project_abe572_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['issue', 'server_side_timestamp'], name='events_even_issue_i_90497b_idx'),
        ),
    ]
