# Generated by Django 4.2.13 on 2024-07-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # the following migrations were previously (auto?) generated here, but the operations below only work on the
        # 'event' model so I don't see how that's correct.
        # ('issues', '0004_rename_event_count_issue_digested_event_count'),
        # ('projects', '0004_project_quota_exceeded_until'),

        ('events', '0009_event_events_even_issue_i_90497b_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ingest_order',
            new_name='digest_order',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('project', 'event_id'), ('issue', 'digest_order')},
        ),
    ]
