# Generated by Django 4.2.13 on 2024-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_ingest_order_event_digest_order_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_project_adcdee_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_issue_i_90497b_idx',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='server_side_timestamp',
            new_name='digested_at',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'never_evict', 'digested_at', 'irrelevance_for_retention'], name='events_even_project_ac6fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['issue', 'digested_at'], name='events_even_issue_i_b18956_idx'),
        ),
    ]
