# Generated by Django 4.2.11 on 2024-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_event_id_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calculated_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='calculated_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
