# Generated by Django 4.2.13 on 2024-07-18 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_events_even_project_adcdee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ingested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
