# Generated by Django 4.2.11 on 2024-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_events_calculated_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ingest_order',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
    ]
