# Generated by Django 4.2.11 on 2024-04-08 19:22

from django.db import migrations


def fill_ingest_order(apps, schema_editor):
    Issue = apps.get_model('issues', 'Issue')
    Event = apps.get_model('events', 'Event')

    for issue in Issue.objects.all():
        for i, event in enumerate(Event.objects.filter(issue=issue).order_by('server_side_timestamp', 'timestamp')):
            event.ingest_order = i + 1
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_ingest_order'),
    ]

    operations = [
        migrations.RunPython(fill_ingest_order),
    ]
