# Generated by Django 4.2.18 on 2025-01-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_alter_turningpoint_options"),
        ("events", "0013_harmonize_foogested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="grouping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="issues.grouping",
            ),
        ),
    ]
