# Generated by Django 4.2.19 on 2025-02-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_remove_event_has_exception_remove_event_has_logentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="storage_backend",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=255, null=True
            ),
        ),
    ]
