# Generated by Django 4.2.19 on 2025-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_event_storage_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageCleanupTodo",
            fields=[
                (
                    "event_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("storage_backend", models.CharField(max_length=255)),
            ],
        ),
    ]
