# Generated by Django 5.2 on 2025-11-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_event_remote_addr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="debug_info",
        ),
    ]
