# Generated by Django 5.2.11 on 2026-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_project_digest_order'),
        ('issues', '0025_alter_grouping_project_alter_issue_project'),
        ('projects', '0016_reset_quota_exceeded_until'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_issue_i_b18956_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['issue', 'digested_at', 'project_digest_order'], name='events_even_issue_i_697148_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['digested_at', 'project_digest_order'], name='events_even_digeste_546933_idx'),
        ),
    ]
