# Generated by Django 5.2.12 on 2026-06-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_events_even_digeste_bf21dd_idx'),
        ('issues', '0025_alter_grouping_project_alter_issue_project'),
        ('projects', '0017_project_issue_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationEventCountsPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bucket', models.DateTimeField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IssueEventCountsPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bucket', models.DateTimeField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('digest_order', models.PositiveIntegerField(null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issues.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'bucket'], name='events_issu_project_c8c750_idx')],
                'unique_together': {('issue', 'bucket')},
            },
        ),
        migrations.CreateModel(
            name='ProjectEventCountsPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bucket', models.DateTimeField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'bucket')},
            },
        ),
    ]
