# Generated by Django 4.2.18 on 2025-02-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["sort_epoch"], name="releases_re_sort_ep_5c07c8_idx"
            ),
        ),
    ]
