# Generated by Django 4.2.13 on 2024-06-23 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_irrelevance_for_retention'),
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turningpoint',
            name='triggering_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.event'),
        ),
    ]
