# Generated by Django 4.2.13 on 2024-07-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_turningpoint_triggering_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='event_count',
            new_name='digested_event_count',
        ),
    ]
