# Generated by Django 4.2.13 on 2024-07-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_rename_event_count_issue_digested_event_count'),  # This is the previous migration

        # The below dependency was previously mentioned here, but there's no need for it, since the operations below
        # don't reference any models from it (explicitly)
        # ('projects', '0004_project_quota_exceeded_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='ingest_order',
            new_name='digest_order',
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('project', 'digest_order')},
        ),
    ]
