# Generated by Django 4.2.13 on 2024-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_rename_ingest_order_issue_digest_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='next_unmute_check',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
