# Generated by Django 4.2.16 on 2024-12-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_issue_next_unmute_check"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="turningpoint",
            options={"ordering": ["-timestamp", "-id"]},
        ),
    ]
