# Generated by Django 4.2.18 on 2025-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_b_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="stored_event_count",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
