# Generated by Django 4.2.19 on 2025-02-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0009_fill_stored_event_count"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["is_resolved", "is_muted", "last_seen"],
                name="issues_issu_is_reso_eaf32b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["is_muted", "last_seen"], name="issues_issu_is_mute_6fe7fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["is_resolved", "last_seen"],
                name="issues_issu_is_reso_0b6923_idx",
            ),
        ),
    ]
