# Generated by Django 4.2.19 on 2025-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_truncate_exception_type_128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="calculated_type",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="issue",
            name="calculated_value",
            field=models.TextField(blank=True, default="", max_length=1024),
        ),
    ]
