# Generated by Django 4.2.11 on 2024-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_create_grouping_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='calculated_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='calculated_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
