# Generated by Django 4.2.11 on 2024-04-09 08:37

from django.db import migrations


def fill_ingest_order(apps, schema_editor):
    Issue = apps.get_model('issues', 'Issue')
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.all():
        for i, issue in enumerate(Issue.objects.filter(project=project).order_by('first_seen')):
            issue.ingest_order = i + 1
            issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_issue_ingest_order'),
    ]

    operations = [
        migrations.RunPython(fill_ingest_order),
    ]
