# Generated by Django 4.2.11 on 2024-04-12 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_fill_denormalized_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0021_issue_last_frame_filename_issue_last_frame_function_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('kind', models.IntegerField(choices=[(1, 'First seen'), (2, 'Resolved'), (3, 'Muted'), (4, 'Regressed'), (5, 'Unmuted'), (100, 'Manual annotation')])),
                ('metadata', models.TextField(default='{}')),
                ('comment', models.TextField(blank=True, default='')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.issue')),
                ('triggering_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
