# Generated by Django 4.2.11 on 2024-05-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0022_turningpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turningpoint',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='turningpoint',
            name='kind',
            field=models.IntegerField(choices=[(1, 'First seen'), (2, 'Resolved'), (3, 'Muted'), (4, 'Marked as regressed'), (5, 'Unmuted'), (10, 'Release info added'), (100, 'Manual annotation')]),
        ),
        migrations.AddIndex(
            model_name='turningpoint',
            index=models.Index(fields=['timestamp'], name='issues_turn_timesta_eaa375_idx'),
        ),
    ]
