# Generated by Django 5.2.12 on 2026-07-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0025_alter_grouping_project_alter_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turningpoint',
            name='kind',
            field=models.IntegerField(choices=[(1, 'First seen'), (2, 'Resolved'), (3, 'Muted'), (4, 'Marked as regressed'), (5, 'Unmuted'), (6, 'Reopened'), (10, 'Release info added'), (100, 'Manual annotation')]),
        ),
    ]
