from django.db import migrations


def set_mechanism_independent_groupings(apps, schema_editor):
    Grouping = apps.get_model("issues", "Grouping")

    # Grouping.objects.update(grouping_mechanism="bugsink-v1")  # Already one-time default in the schema-migration

    # We try as best as we can to detect whether historical groupings were generated by the default grouper or by an
    # explicit SDK fingerprint (containing no default). This cannot be done with 100% accuracy because the grouping does
    # not record the fingerprint that generated it.
    #
    # Howver, we can at least have the following 90% solution: items without " ⋄ " in their grouping key must have come
    # from an explicit SDK fingerprint, because the default grouper always included " ⋄ " in its grouping key (it always
    # appended the transaction, so it always had at least 2 joined parts).
    #
    # Multi-part fixed-text fingerprints (["foo", "bar"]) will be misclassified under this scheme, for which there is
    # another piece of legacy-handling code in the digest path.
    Grouping.objects.exclude(grouping_key__contains=" ⋄ ").update(grouping_mechanism="none")


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0029_grouping_mechanism"),
    ]

    operations = [
        migrations.RunPython(set_mechanism_independent_groupings, migrations.RunPython.noop),
    ]
