# Generated by Django 5.2.15 on 2026-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0031_grouping_mechanism_unique'),
        ('projects', '0018_project_grouping_mechanism'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_resolved', 'is_muted', 'last_seen'], name='issue_global_open'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_muted', 'last_seen'], name='issue_global_muted'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_resolved', 'last_seen'], name='issue_global_resolved'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['last_seen'], name='issue_global_all'),
        ),
    ]
