# Generated by Django 5.2.12 on 2026-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0032_issue_issue_global_open_issue_issue_global_muted_and_more'),
        ('projects', '0019_alter_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_list_muted',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_list_resolved',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_global_muted',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_global_resolved',
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'is_resolved', 'is_muted', 'digested_event_count', 'last_seen'], name='issue_count_open'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'digested_event_count', 'last_seen'], name='issue_count_all'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_resolved', 'is_muted', 'digested_event_count', 'last_seen'], name='issue_global_count_open'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['digested_event_count', 'last_seen'], name='issue_global_count_all'),
        ),
    ]
