# Generated by Django 5.2.18 on 2026-10-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0033_remove_issue_issue_list_muted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='last_realerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turningpoint',
            name='kind',
            field=models.IntegerField(choices=[(1, 'First seen'), (2, 'Resolved'), (3, 'Muted'), (4, 'Marked as regressed'), (5, 'Unmuted'), (6, 'Reopened'), (10, 'Release info added'), (11, 'Still open'), (100, 'Manual annotation')]),
        ),
    ]
