# Generated by Django 5.2.18 on 2026-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0033_remove_issue_issue_list_muted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='level',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
