# Generated by Django 4.2.18 on 2025-02-03 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_b_squashed_initial"),  # defines the Team model, which we have a FK to
        ("projects", "0001_initial"),  # this is the previous migration
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="digested_event_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="next_quota_check",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="quota_exceeded_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_max_event_count",
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                default=1,  # unused; this migration is run against no-rows
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="visibility",
            field=models.IntegerField(
                choices=[(1, "Joinable"), (10, "Discoverable"), (99, "Team Members")],
                default=99,
                help_text="Which users can see this project and its issues?",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together={("project", "user")},
        ),
    ]
