# Generated by Django 4.2.18 on 2025-02-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_b_squashed_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["name"], name="projects_pr_name_11d782_idx"),
        ),
    ]
