# Generated by Django 4.2.13 on 2024-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_retention_max_event_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quota_exceeded_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
