# Generated by Django 4.2.13 on 2024-07-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_initial_ingested_count_value'),
    ]

    operations = [
        # this works because the data is filled with "best guess" values anyway and nobody but the Bugsink developers
        # themselves will be affected by this rename.
        migrations.RenameField(
            model_name='project',
            old_name='ingested_event_count',
            new_name='digested_event_count',
        ),
    ]
