# Generated by Django 4.2.13 on 2024-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_ingested_event_count_project_digested_event_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_quota_check',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
