# Generated by Django 4.2.18 on 2025-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_projects_pr_name_11d782_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="stored_event_count",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
