# Generated by Django 4.2.21 on 2025-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_fill_stored_event_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
