# Generated by Django 4.2.13 on 2024-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectmembership_send_email_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Joinable'), (10, 'Visible'), (99, 'Hidden')], default=99),
        ),
    ]
