# Generated by Django 4.2.23 on 2025-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projectmembership_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blame_ref_tag',
            field=models.CharField(blank=True, help_text='Which event tag will be used to find the git-ref while locating the blame?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='blame_template',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
