# Generated by Django 5.2.11 on 2026-03-17 10:45

from django.db import migrations, models


def unfill_issue_count(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.all().update(issue_count=0)


def fill_issue_count(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Issue = apps.get_model("issues", "Issue")
    for project in Project.objects.all():
        project.issue_count = Issue.objects.filter(project_id=project.id, is_deleted=False).count()
        project.save(update_fields=["issue_count"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_reset_quota_exceeded_until'),
        ('issues', '0025_alter_grouping_project_alter_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(fill_issue_count, unfill_issue_count),
    ]
