# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_grouping_mechanism'),
        ('teams', '0002_team_teams_team_name_43e047_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='unique_project_name_per_team'),
        ),
    ]
