# Generated by Django 5.2.18 on 2026-10-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mute_volume',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='new_issues_start_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='noise_period',
            field=models.CharField(choices=[('minute', 'Minutes'), ('hour', 'Hours'), ('day', 'Days'), ('week', 'Weeks'), ('month', 'Months'), ('year', 'Years')], default='day', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='realert_after_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='realert_after_events',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='unmute_volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
