# Generated by Django 4.2.16 on 2024-11-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonehome", "0004_installation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="silence_email_system_warning",
            field=models.BooleanField(default=False),
        ),
    ]
