# Generated by Django 4.2.11 on 2024-04-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_event_ingested_event'),
        ('ingest', '0004_set_sqlite_wal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecompressedEvent',
        ),
    ]
