# Generated by Django 4.2.11 on 2024-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snappea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('args', models.TextField(default='[]')),
                ('kwargs', models.TextField(default='{}')),
            ],
        ),
    ]
