# Generated by Django 4.2.18 on 2025-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snappea", "0003_task_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["created_at"], name="snappea_tas_created_eb0824_idx"
            ),
        ),
    ]
