# Generated by Django 4.2.19 on 2025-04-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snappea", "0004_task_snappea_tas_created_eb0824_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("task_name", models.CharField(max_length=255)),
                ("task_count", models.PositiveIntegerField(null=True)),
                ("done", models.PositiveIntegerField()),
                ("errors", models.PositiveIntegerField()),
                ("wall_time", models.FloatField()),
                ("wait_time", models.FloatField()),
                ("write_time", models.FloatField()),
                ("max_wall_time", models.FloatField()),
                ("max_wait_time", models.FloatField()),
                ("max_write_time", models.FloatField()),
            ],
            options={
                "unique_together": {("timestamp", "task_name")},
            },
        ),
    ]
