# Generated by Django 4.2.19 on 2025-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="eventtag",
            name="tags_eventt_value_i_255b9c_idx",
        ),
        migrations.AddField(
            model_name="eventtag",
            name="digest_order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="eventtag",
            index=models.Index(
                fields=["value", "issue", "digest_order"],
                name="tags_eventt_value_i_6f1823_idx",
            ),
        ),
    ]
