# Generated by Django 4.2.23 on 2025-07-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_messagingserviceconfig_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingserviceconfig',
            name='last_failure_error_message',
            field=models.TextField(blank=True, help_text='Error message from the exception', null=True),
        ),
        migrations.AddField(
            model_name='messagingserviceconfig',
            name='last_failure_error_type',
            field=models.CharField(blank=True, help_text="Type of error that occurred (e.g., 'requests.HTTPError')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagingserviceconfig',
            name='last_failure_is_json',
            field=models.BooleanField(blank=True, help_text='Whether the response was valid JSON', null=True),
        ),
        migrations.AddField(
            model_name='messagingserviceconfig',
            name='last_failure_response_text',
            field=models.TextField(blank=True, help_text='Response text from the failed request', null=True),
        ),
        migrations.AddField(
            model_name='messagingserviceconfig',
            name='last_failure_status_code',
            field=models.IntegerField(blank=True, help_text='HTTP status code of the failed request', null=True),
        ),
        migrations.AddField(
            model_name='messagingserviceconfig',
            name='last_failure_timestamp',
            field=models.DateTimeField(blank=True, help_text='When the last failure occurred', null=True),
        ),
    ]
