# Generated by Django 5.2.8 on 2025-11-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_messagingserviceconfig_last_failure_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingserviceconfig',
            name='kind',
            field=models.CharField(choices=[('slack', 'Slack (or compatible)'), ('discord', 'Discord')], default='slack', max_length=20),
        ),
    ]
