# Generated by Django 4.2.19 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_chunk_created_at_file_accessed_at_file_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="storage_backend",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=255, null=True
            ),
        ),
    ]
