# Generated by Django 4.2.21 on 2025-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_chunk_created_at_file_accessed_at_file_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
    ]
