# Generated by Django 5.2.12 on 2026-05-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_storage_backend'),
        ('projects', '0017_project_issue_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filemetadata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='project',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project'
            ),
        ),
        migrations.AddConstraint(
            model_name='filemetadata',
            constraint=models.UniqueConstraint(condition=models.Q(('debug_id__isnull', False), ('file_type__isnull', False), ('project__isnull', False)), fields=('project', 'debug_id', 'file_type'), name='filemeta_project_debug_type'),
        ),
        migrations.AddConstraint(
            model_name='filemetadata',
            constraint=models.UniqueConstraint(condition=models.Q(('debug_id__isnull', False), ('file_type__isnull', False), ('project__isnull', True)), fields=('debug_id', 'file_type'), name='filemeta_legacy_debug_type'),
        ),
    ]
